[tool.ruff]
src = ["src"]
line-length = 120

[tool.ruff.lint]

# I: isort-compatible import sorting
# W291: Trailing whitespace
# W292: Add newline to end of file
extend-select = ["I", "W292", "W291"]

[tool.pyright]
include = ["src"]
exclude = ["**/__pycache__",
    "notebooks",
]
extraPaths = ["src"]
reportIncompatibleMethodOverride = false
reportIncompatibleVariableOverride = false

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
