[tool.ruff]
src = ["src"]

[tool.ruff.lint]

# I: isort-compatible import sorting
# W291: Trailing whitespace
# W292: Add newline to end of file
extend-select = ["I", "W292", "W291"]

[tool.pyright]
include = ["src/fundus_murag"]
exclude = ["**/__pycache__",
    "notebooks",
]
extraPaths = ["src/fundus_murag"]
reportIncompatibleMethodOverride = false
reportIncompatibleVariableOverride = false
