# This config assumes that the app is started within the Docker container. Usually, you only need to change the values in the <...> placeholders.

# Logging configuration
logging:
  dir: /data/logs
  level: INFO

# Data files configuration
data:
  records_df_file: /data/records.pq
  collections_df_file: /data/collections.pq
  record_embeddings_df_file: /data/record_embeddings.pq
  collections_embeddings_df_file: /data/collection_embeddings.pq
  user_image_dir: /data/user_images

# Application settings
app:
  dev_mode: False
  reset_vdb_on_startup: False

# Weaviate database configuration
weaviate:
  host: weaviate
  http_port: 8080  # Keep this as is unless you changed the port in the `docker/docker-compose.yaml` file
  grpc_port: 50051  # Keep this as is unless you changed the port in the `docker/docker-compose.yaml` file

# Google Cloud configuration
google:
  project_id: <GOOGLE_PROJECT_ID>
  default_location: "us-central1"
  application_credentials_file: <PATH_TO_GOOGLE_APPLICATION_CREDENTIALS_FILE>

# OpenAI configuration
openai:
  api_key: <OPEN_AI_API_KEY>

# FUNDus service configuration
fundus:
  ml_url: http://fundus-murag-ml:<FUNDUS_ML_EXPOSED>  # Use the port you defined in the .env.prod file in the `docker` folder

# Assistant configuration
assistant:
  default_model: "google/gemini-2.0-flash"

# MLFlow configuration
mlflow:
  host: mlflow
  port: 5000
