# This config assumes that the app is started from the root of the project in a development environment. Usually, you only need to change the values in the <...> placeholders.

# Logging configuration
logging:
  dir: logs
  level: DEBUG

# Data files configuration
data:
  records_df_file: /ltstorage/shares/projects/fundus-murag/dataframes/records.pq
  collections_df_file: /ltstorage/shares/projects/fundus-murag/dataframes/collections.pq
  record_embeddings_df_file: /ltstorage/shares/projects/fundus-murag/dataframes/record_embeddings.pq
  collections_embeddings_df_file: /ltstorage/shares/projects/fundus-murag/dataframes/collection_embeddings.pq
  fundus_data_root: /ltstorage/shares/projects/fundus-murag/fundus-json
  user_image_dir: data/user_images

# Application settings
app:
  dev_mode: True
  reset_vdb_on_startup: True

# Weaviate database configuration
weaviate:
  host: localhost
  http_port: <WEAVIATE_HTTP_EXPOSED>
  grpc_port: <WEAVIATE_GRPC_EXPOSED>

# Google Cloud configuration
google:
  project_id: <GOOGLE_PROJECT_ID>
  default_location: "us-central1"
  application_credentials_file: <PATH_TO_GOOGLE_APPLICATION_CREDENTIALS_FILE>

# OpenAI configuration
openai:
  api_key: <OPEN_AI_API_KEY>

# FUNDus service configuration
fundus:
  ml_url: http://localhost:<FUNDUS_ML_EXPOSED>

# Assistant configuration
assistant:
  default_model: "google/gemini-2.0-flash"

# MLFlow configuration
mlflow:
  host: localhost
  port: <MLFLOW_EXPOSED>
