# this config assumes that the app is started from the root of the project in a development environment. . Usually, you only need to change the values in the <...> placeholders.

# the path to the records dataframe file
fundus_records_df_file: data/records.pq
# the path to the collections dataframe file
fundus_collections_df_file: data/collections.pq
# the path to the record embeddings dataframe file
fundus_record_embeddings_df_file: data/record_embeddings.pq
# the path to the collection embeddings dataframe file
fundus_collections_embeddings_df_file: data/collection_embeddings.pq

# whether the app is in dev mode
dev_mode: True
# whether to reset the vector database on startup
reset_vdb_on_startup: True

# the host of the weaviate instance
weaviate_host: localhost
# the http port of the weaviate instance. Use the port you defined in the `.env.dev` file in the `docker` folder
weaviate_http_port: <WEAVIATE_HTTP_EXPOSED>
# the grpc port of the weaviate instance. Use the port you defined in the `.env.dev` file in the `docker` folder
weaviate_grpc_port: <WEAVIATE_GRPC_EXPOSED>

# the google project id
google_project_id: <GOOGLE_PROJECT_ID>
# the path to the google application credentials file
google_application_credentials_file: <PATH_TO_GOOGLE_APPLICATION_CREDENTIALS_FILE>

# the url to the FUNDus ML service. Check the logs of the FUNDus ML service to see the port it is running on. Use the port defined in the `.env.dev` file in the `docker` folder. If running the FUNDus ML service locally, check the logs of the FUNDus ML service to see the port it is running on.
fundus_ml_url: http://localhost:<FUNDUS_ML_EXPOSED>