fundus_records_df_file: /data/records.pq
fundus_collections_df_file: /data/collections.pq
fundus_record_embeddings_df_file: /data/record_embeddings.pq
fundus_collections_embeddings_df_file: /data/collection_embeddings.pq

dev_mode: False
reset_vdb_on_startup: False

weaviate_host: weaviate
weaviate_http_port: 8080
weaviate_grpc_port: 50051

google_project_id: gen-lang-client-0929280396
google_application_credentials_file: /data/gen-lang-client-0929280396-6db326cbaefc.json

fundus_ml_url: http://fundus-murag-ml:58003
fundus_data_url: http://fundus-data:58004